In [11]:
#180509
#SarahFong

#The purpose of this script is to merge back together.
#.Bed files cannot have headers to perform a merge. 
#Then, to find meaningful enhancer signal among the fragments generated.

import os
import pandas

In [19]:
path = '/dors/capra_lab/users/fongsl/broadly_active_enhancers/data/roadmap_multi_data/'

# The resultant multiintersect_roadmap_enhancer.bed file
# Enhancers for each roadmap sample were stringently defined as H3K27AC with no overlapping H3K4me3 peaks

input_bed = 'short_multiintersect_roadmap.bed'

In [6]:
#Merge fragments that are within 100 bases of one another
#Collect a string of the samples the fragments come from, separated with a comma delimiter

cmd= "mergeBed -i %s/%s -d 100 -c 4 -o collapse -delim ','> %s/merged_%s"% (path, input_bed, path, input_bed)
print(cmd)

mergeBed -i /dors/capra_lab/users/fongsl/broadly_active_enhancers/data/roadmap_multi_data/short_multiintersect_roadmap.bed -d 100 -c 4 -o collapse -delim ','> /dors/capra_lab/users/fongsl/broadly_active_enhancers/data/roadmap_multi_data/merged_short_multiintersect_roadmap.bed

In [7]:
os.system(cmd)

0

In [66]:
# this merged file will serve as the genome reference

merged = "%smerged_%s"% (path, input_bed)
multi = "%s%s" % (path, input_bed)

In [74]:
dfm = pandas.read_table(merged, sep = '\t')
dfmg = pandas.read_table(multi, sep = '\t')

In [68]:
dfm[4]= dfm["3"].str.split(",").str.len()

In [97]:
# what if I just look at peaks in the 99% of intersected fragments?
dfmg["length"] = dfmg['2']-dfmg['1']
db= dfmg.loc[dfmg['3']>=dfmg['3'].quantile(0.99)]
print(db.head())
db.shape
db.to_csv("%s99_%s"% (path, input_bed), sep='\t', index = False, header = False)

         0        1        2   3  \
1739  chr1  1440605  1440986  37
3418  chr1  1757952  1757964  37
3419  chr1  1757964  1757995  38
3420  chr1  1757995  1758058  39
3421  chr1  1758058  1758065  40

                                                      4  length
1739  2,5,6,7,8,10,14,16,20,21,22,25,31,34,39,40,43,...     381
3418  2,3,5,9,10,14,17,20,22,23,25,29,31,32,35,37,38...      12
3419  2,3,5,9,10,13,14,17,20,22,23,25,29,31,32,35,37...      31
3420  2,3,5,9,10,13,14,17,20,22,23,25,29,31,32,35,37...      63
3421  2,3,5,9,10,13,14,17,20,22,23,25,29,31,32,35,37...       7

In [69]:
dfm.head()

      0      1      2                          3   4
0  chr1   9998  10563  1,2,3,4,5,6,7,6,5,4,3,2,1  13
1  chr1  13045  15115                      1,2,1   3
2  chr1  16072  16614                          1   1
3  chr1  19949  20313                          1   1
4  chr1  78919  79787                          1   1

In [29]:
c = dfm[:3]
print(c.head())
c.to_csv("%sc.bed" %path, index = False, header = False, sep = '\t')

      0      1      2                          3
0  chr1   9998  10563  1,2,3,4,5,6,7,6,5,4,3,2,1
1  chr1  13045  15115                      1,2,1
2  chr1  16072  16614                          1

In [43]:
cmd = "bedtools genomecov -i %sa.bed -g %sc.bed -d> %sd.bed"% (path, path, path)
print(cmd)

bedtools genomecov -i /dors/capra_lab/users/fongsl/broadly_active_enhancers/data/roadmap_multi_data/a.bed -g /dors/capra_lab/users/fongsl/broadly_active_enhancers/data/roadmap_multi_data/c.bed -d> /dors/capra_lab/users/fongsl/broadly_active_enhancers/data/roadmap_multi_data/d.bed

In [44]:
os.system(cmd)

0

In [22]:
pwd

'/dors/capra_lab/users/fongsl/broadly_active_enhancers/baes/roadmap_multi'

In [47]:
a = pandas.read_table("%sa.bed" %path, sep='\t', header = -1)
c = pandas.read_table("%sc.bed" %path, sep='\t', header = -1)
d = pandas.read_table("%sd.bed" %path, sep='\t', header = -1)
d1 = d.loc[d[2] !=0]

In [ ]:
print("Multi Intersect before merge", a,"\n")
print("Multi Intersect after merge", c,"\n")
print("Multi Intersect x merge genome coverage", d,"\n")

In [48]:
d1

          0      1  2
9998   chr1   9999  1
9999   chr1  10000  1
10000  chr1  10001  1
10001  chr1  10002  1
10002  chr1  10003  1
10003  chr1  10004  1
10004  chr1  10005  1
10005  chr1  10006  1
10006  chr1  10007  1
10007  chr1  10008  1
10008  chr1  10009  1
10009  chr1  10010  1
10010  chr1  10011  1
10011  chr1  10012  1
10012  chr1  10013  1
10013  chr1  10014  1
10014  chr1  10015  1
10015  chr1  10016  1
10016  chr1  10017  1
10017  chr1  10018  1
10018  chr1  10019  1
10019  chr1  10020  1
10020  chr1  10021  1
10021  chr1  10022  1
10022  chr1  10023  1
10023  chr1  10024  1
10024  chr1  10025  1
10025  chr1  10026  1
10026  chr1  10027  1
10027  chr1  10028  1
...     ...    ... ..
10072  chr1  10073  1
10073  chr1  10074  1
10074  chr1  10075  1
10075  chr1  10076  1
10076  chr1  10077  1
10077  chr1  10078  1
10078  chr1  10079  1
10079  chr1  10080  1
10080  chr1  10081  1
10081  chr1  10082  1
10082  chr1  10083  1
10083  chr1  10084  1
10084  chr1  10085  1
10085  chr1  10086  1
10086  chr1  10087  1
10087  chr1  10088  1
10088  chr1  10089  1
10089  chr1  10090  1
10090  chr1  10091  1
10091  chr1  10092  1
10092  chr1  10093  1
10093  chr1  10094  1
10094  chr1  10095  1
10095  chr1  10096  1
10096  chr1  10097  1
10097  chr1  10098  1
10098  chr1  10099  1
10099  chr1  10100  1
10100  chr1  10101  1
10101  chr1  10102  1

[104 rows x 3 columns]